project:
  type: website
  output-dir: docs

website:
  title: "Computer Vision for Beginners"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ProfessorPolymorphic/CVPrimer

format:
  html:
    theme: spacelab
    css: styles.css



